#!/usr/bin/env python3
"""Englische Fassung aller Unterseiten-Texte.

Schlüssel = der deutsche Text exakt so, wie er in `baue-unterseiten.py` steht.
Nach jeder Änderung: python3 scripts/baue-i18n.py
"""

EN = {
    "Gehwege &amp; Einfahrten reinigen": "Cleaning paths &amp; driveways",
    "Die Fläche, die jeder Besucher zuerst betritt.": "The surface every visitor steps on first.",
    "Warum Einfahrten grau werden": "Why driveways turn grey",
    "Diese Beläge reinigen wir": "Surfaces we clean",
    "Betonpflaster und Verbundsteine": "Concrete block and interlocking pavers",
    "Waschbeton und Betonplatten": "Exposed aggregate and concrete slabs",
    "Natursteinpflaster und Kopfsteinpflaster": "Natural stone and cobble paving",
    "Asphalt und Teerdecken": "Asphalt and tarmac",
    "Gehwegplatten aller Formate": "Paving slabs in all formats",
    "Wie lange dauert eine Einfahrt?": "How long does a driveway take?",
    "Wird der Stein durch den Hochdruck beschädigt?": "Does high pressure damage the stone?",
    "Was passiert mit den Pflanzen am Rand?": "What happens to the plants at the edges?",
    "Wir decken Beete und empfindliche Bepflanzung ab. Die von uns eingesetzten Mittel sind biologisch abbaubar.": "We cover beds and delicate planting. The products we use are biodegradable.",
    "Kommt der Grünbelag wieder?": "Will the green growth come back?",
    "Ohne Imprägnierung nach zwei bis drei Jahren, je nach Lage. Mit Imprägnierung deutlich später — und wenn er innerhalb der fünf Jahre stark zurückkommt, reinigen wir kostenlos nach.": "Without sealing, after two to three years depending on the location. With sealing, considerably later — and if it returns heavily within the five years, we clean again free of charge.",
    "Dach &amp; Überdachung reinigen": "Cleaning roofs &amp; canopies",
    "Moos kostet das Dach Lebensdauer. Nicht Optik.": "Moss costs the roof its lifespan. Not its looks.",
    "Warum Moos auf dem Dach ein Problem ist": "Why moss on a roof is a problem",
    "Von der Traufe zum First": "From eaves to ridge",
    "Diese Dächer reinigen wir": "Roofs and canopies we clean",
    "Ton- und Betondachziegel": "Clay and concrete roof tiles",
    "Blech- und Trapezdächer": "Sheet metal and trapezoidal roofs",
    "Carports und Garagendächer": "Carports and garage roofs",
    "Terrassenüberdachungen aus Glas oder Kunststoff": "Patio roofs in glass or plastic",
    "Wintergärten von außen": "Conservatories from the outside",
    "Steigen Sie auf jedes Dach?": "Do you go up on every roof?",
    "Ist eine Reinigung besser als eine Neueindeckung?": "Is cleaning better than a new roof covering?",
    "Was ist mit einer Dachbeschichtung?": "What about a roof coating?",
    "Wie lange dauert ein Einfamilienhaus?": "How long does a detached house take?",
    "Terrasse &amp; Naturstein reinigen": "Cleaning patios &amp; natural stone",
    "Empfindliche Beläge vertragen keinen groben Druck.": "Delicate surfaces cannot take rough pressure.",
    "Warum Naturstein Sonderbehandlung braucht": "Why natural stone needs special treatment",
    "Marmor und Kalkstein": "Marble and limestone",
    "Granit und Basalt": "Granite and basalt",
    "Sandstein und Travertin": "Sandstone and travertine",
    "Treppen, Podeste und Eingangsbereiche": "Steps, landings and entrance areas",
    "Kann Naturstein durch Reinigung stumpf werden?": "Can cleaning make natural stone dull?",
    "Bekommen Sie Rotweinflecken und Fett heraus?": "Can you get out red wine stains and grease?",
    "Wie oft sollte man eine Terrasse reinigen?": "How often should a patio be cleaned?",
    "Die Alternative zum Neuanstrich — zu einem Bruchteil.": "The alternative to repainting — at a fraction of the cost.",
    "Grünbelag ist kein Anstrichproblem": "Green growth is not a paint problem",
    "Biologisch abbaubare Mittel": "Biodegradable products",
    "Diese Fassaden reinigen wir": "Facades we clean",
    "Mineralischer und Kunstharzputz": "Mineral and synthetic resin render",
    "Klinker und Verblendmauerwerk": "Brick and facing masonry",
    "Sichtbeton": "Fair-faced concrete",
    "Hält die Reinigung auch bei starkem Befall?": "Does cleaning work even with heavy growth?",
    "Brauchen Sie ein Gerüst?": "Do you need scaffolding?",
    "In der Regel ein bis zwei Tage, abhängig von Fläche und Verschmutzung.": "As a rule one to two days, depending on area and level of soiling.",
    "Imprägnierung &amp; Versiegelung": "Sealing &amp; impregnation",
    "Warum eine Reinigung allein nicht reicht": "Why cleaning alone is not enough",
    "Fünf Jahre Garantie": "Five-year guarantee",
    "Was wir imprägnieren": "What we seal",
    "Terrassen aus Stein und Beton": "Patios in stone and concrete",
    "Dachflächen nach der Reinigung": "Roof surfaces after cleaning",
    "Treppen und Eingänge": "Steps and entrances",
    "Verändert die Imprägnierung die Optik?": "Does sealing change the appearance?",
    "Wird die Fläche rutschig?": "Does the surface become slippery?",
    "Was deckt die Fünf-Jahres-Garantie ab?": "What does the five-year guarantee cover?",
    "Kann man das später nachholen?": "Can it be done later?",
    "Wie wir arbeiten": "How we work",
    "Die Anfahrt ist kostenlos": "Travel is free of charge",
    "Sie bekommen danach einen festen Preis": "Afterwards you get a fixed price",
    "Die Probefläche kostet nichts und dauert eine halbe Stunde.": "The test area costs nothing and takes half an hour.",
    "ENTWURF für Julien Ebert — nicht veröffentlichen. Bilder, Preise und Bewertungen sind Platzhalter.": "DRAFT for Julien Ebert — do not publish. Images, prices and reviews are placeholders.",
    "Pflaster und Beton haben feine Poren. Über die Jahre setzt sich dort Staub fest, der Regen wäscht ihn ein. So wird aus der ursprünglichen Farbe ein gleichmäßiges Grau. Diesen Schmutz kann man nicht wegkehren. Er sitzt im Stein.": "Paving and concrete have fine pores. Over the years dust settles in them and the rain washes it in. The original colour turns into an even grey. You cannot sweep this dirt away. It sits inside the stone.",
    "Dazu kommt das Grün. Algen und Moos brauchen nur Feuchtigkeit und etwas Schatten. In den Fugen finden sie beides. Was dort wächst, hält die Nässe im Stein. Der Belag altert dadurch schneller.": "Then there is the green. Algae and moss only need moisture and a little shade. The joints offer both. Whatever grows there holds damp in the stone, and the surface ages faster.",
    "Ein Gerät, das den Druck gleichmäßig verteilt": "A machine that spreads the pressure evenly",
    "Wer mit einem einfachen Strahl über den Stein geht, hinterlässt Streifen. Wir arbeiten mit einem Gerät, das den Druck gleichmäßig verteilt. So bleiben keine Streifen und keine ausgewaschenen Stellen zurück.": "A plain jet run across the stone leaves streaks. We use a machine that spreads the pressure evenly. No streaks and no washed-out patches are left behind.",
    "Wir stellen den Druck auf Ihren Stein ein": "We set the pressure to suit your stone",
    "Nicht jeder Stein verträgt gleich viel. Betonpflaster hält mehr aus als Waschbeton, Waschbeton mehr als Naturstein. Wir stellen den Druck für jede Fläche neu ein. Das dauert länger. Dafür bleibt Ihr Stein heil.": "Not every stone takes the same treatment. Concrete block takes more than exposed aggregate, and that takes more than natural stone. We set the pressure for each surface. It takes longer. In return your stone stays intact.",
    "Fugen spülen und wieder auffüllen": "Flush the joints and fill them again",
    "Beim Reinigen löst sich immer etwas Fugenmaterial. Wird es nicht ersetzt, wackeln die Steine schon nach einem Jahr. Wir füllen die Fugen wieder auf. Auf Wunsch mit einem Material, in dem kein Unkraut mehr wächst.": "Cleaning always loosens some joint material. If it is not replaced, the stones wobble within a year. We fill the joints again. On request with a material in which no weeds grow.",
    "Zum Schluss eine Schutzschicht": "A protective layer at the end",
    "Die Schutzschicht schließt die Poren im Stein. Wasser perlt ab, Schmutz hält nicht mehr, und das Grün kommt viel später zurück. Darauf geben wir fünf Jahre Garantie.": "The protective layer closes the pores in the stone. Water beads off, dirt no longer sticks, and the green comes back much later. We give a five-year guarantee on it.",
    "Eine normale Einfahrt schaffen wir meist an einem Tag, die Fugen inklusive. Kommt eine Schutzschicht dazu, muss die Fläche vorher einen Tag trocknen.": "We usually finish a normal driveway in a day, joints included. If a protective layer is added, the surface has to dry for a day first.",
    "Nein, wenn der Druck richtig eingestellt ist. Schäden entstehen fast immer, wenn jemand mit einem harten Strahl zu nah an den Stein geht. Genau das machen wir nicht.": "No, not if the pressure is set correctly. Damage almost always happens when someone holds a hard jet too close to the stone. That is exactly what we do not do.",
    "Beton und Estrich": "Concrete and screed",
    "Moos sieht nicht nur alt aus. Es hält Wasser fest. Ein bemooster Ziegel trocknet nach Regen viel langsamer. Bei Frost gefriert dieses Wasser im Ziegel und sprengt ihn nach und nach auf. So wird der Ziegel kaputt, lange bevor er alt ist.": "Moss does not just look old. It holds water. A mossy tile dries much more slowly after rain. In frost that water freezes inside the tile and breaks it apart bit by bit. The tile is ruined long before it is old.",
    "Dazu kommt: Was sich vom Dach löst, landet in der Dachrinne. Ist die Rinne verstopft, läuft das Wasser an der Hauswand herunter. Im schlimmsten Fall wird die Mauer feucht. Deshalb reinigen wir immer beides.": "And there is more: whatever comes off the roof ends up in the gutter. If the gutter is blocked, water runs down the wall of the house. At worst the masonry gets damp. That is why we always clean both.",
    "Wir arbeiten von unten nach oben. So wird kein Wasser unter die Ziegel gedrückt. Genau hier machen unerfahrene Firmen den Fehler, der ein Dach beschädigt.": "We work from the bottom upwards. That way no water is forced under the tiles. This is exactly where inexperienced firms make the mistake that damages a roof.",
    "Der Druck passt zu Ihrem Dach": "The pressure suits your roof",
    "Ein Betonstein hält mehr aus als ein alter Tonziegel. Wir schauen uns Ihr Dach an, bevor wir anfangen. Und wir sagen es Ihnen ehrlich, wenn eine Fläche nicht mehr zu reinigen ist.": "A concrete tile takes more than an old clay tile. We look at your roof before we start. And we tell you honestly if a surface can no longer be cleaned.",
    "Die Dachrinne machen wir mit": "We do the gutter as well",
    "Nach der Reinigung räumen wir Dachrinne und Fallrohr frei und prüfen, ob das Wasser abläuft. Das kostet nichts extra. Das gehört dazu.": "After cleaning we clear the gutter and downpipe and check that the water runs away. There is no extra charge. It is part of the job.",
    "Schutz, damit das Moos nicht gleich wiederkommt": "Protection so the moss does not come straight back",
    "Auf Wunsch behandeln wir das saubere Dach nach. Dann kommen Moos und Flechten nicht so schnell zurück. Auch darauf geben wir fünf Jahre Garantie.": "On request we treat the clean roof afterwards. Then moss and lichen do not return so quickly. We give a five-year guarantee on that too.",
    "Auf die meisten. Wenn das Dach es nicht trägt, arbeiten wir vom Gerüst, von einer Hebebühne oder mit einer langen Stange vom Boden aus. Was bei Ihnen geht, sehen wir vor Ort.": "Most of them. If the roof will not take our weight, we work from scaffolding, a lift platform, or with a long pole from the ground. We see what works at your place on site.",
    "Fast immer, solange die Ziegel heil sind. Ein neues Dach kostet ein Vielfaches. Wenn Ihr Dach wirklich nicht mehr zu retten ist, sagen wir Ihnen das offen.": "Almost always, as long as the tiles are sound. A new roof costs many times more. If your roof really is beyond saving, we tell you openly.",
    "Eine Beschichtung ist Farbe auf dem Ziegel. Sie kann sinnvoll sein. Ohne gründliche Reinigung vorher hält sie aber nicht. Wir sagen Ihnen ehrlich, was Ihr Dach braucht.": "A coating is paint on the tile. It can make sense. But without a thorough clean beforehand it will not last. We tell you honestly what your roof needs.",
    "Ein bis zwei Tage, je nach Größe und Verschmutzung. Die Dachrinne ist dabei.": "One to two days, depending on size and how dirty it is. The gutter is included.",
    "Faserzement und Wellplatten (Eternit)": "Fibre cement and corrugated sheets",
    "Naturstein ist nicht gleich Naturstein. Marmor und Kalkstein vertragen keine scharfen Mittel. Sandstein ist weich und geht bei zu viel Druck kaputt. Granit hält fast alles aus. Wer alle Steine gleich behandelt, macht die Hälfte davon kaputt.": "Natural stone is not all the same. Marble and limestone cannot take harsh products. Sandstone is soft and breaks up under too much pressure. Granite takes almost anything. Treat every stone the same and you ruin half of them.",
    "Eine Terrasse grenzt meist direkt ans Haus. Wasser und Reinigungsmittel dürfen nicht in die Fuge zur Hauswand oder in die Kellerschächte laufen. Das ist eine Frage von Sorgfalt, nicht von Kraft.": "A patio usually adjoins the house. Water and cleaning products must not run into the joint against the wall or into the basement wells. That is a question of care, not of force.",
    "Zuerst schauen wir, um welchen Stein es geht": "First we work out which stone it is",
    "Wir schauen uns Ihren Stein genau an und wählen danach Druck und Mittel. An einer Stelle, die man nicht sieht, testen wir das Ergebnis. Erst dann machen wir weiter.": "We look closely at your stone and choose the pressure and product to match. We test the result in a spot nobody sees. Only then do we carry on.",
    "Wenig Druck und Bürste, wo es nötig ist": "Low pressure and a brush where needed",
    "Bei weichem Sandstein oder Marmor arbeiten wir mit wenig Druck und einer Bürste. Das dauert länger. Dafür bleibt die Oberfläche schön.": "On soft sandstone or marble we work with low pressure and a brush. It takes longer. In return the surface stays beautiful.",
    "Kanten und Stufen machen wir von Hand": "We do edges and steps by hand",
    "Treppenkanten und den Übergang zur Hauswand machen wir von Hand nach. Genau dort sieht man später, ob sauber gearbeitet wurde.": "We finish step edges and the join with the house wall by hand. That is exactly where you can see later whether the work was done properly.",
    "Eine Schutzschicht, die zu Ihrem Stein passt": "A protective layer that suits your stone",
    "Naturstein braucht eine andere Schutzschicht als Beton. Wir nehmen eine, die den Stein atmen lässt.": "Natural stone needs a different protective layer than concrete. We use one that lets the stone breathe.",
    "Ja, wenn das falsche Mittel benutzt wird oder der Druck zu hoch ist. Polierte Steine sind besonders empfindlich. Deshalb prüfen wir vorher und testen an einer verdeckten Stelle.": "Yes, if the wrong product is used or the pressure is too high. Polished stone is especially sensitive. That is why we check first and test in a hidden spot.",
    "Meistens ja. Ganz ehrlich: nicht immer vollständig. Öl zieht tief in den Stein ein. Bei der Probefläche sehen Sie, was wirklich geht. Wir versprechen Ihnen nichts, was wir nicht halten können.": "Usually yes. To be honest: not always completely. Oil soaks deep into the stone. The test area shows you what is really possible. We promise you nothing we cannot keep.",
    "Wie kommt der Preis zustande?": "How is the price worked out?",
    "Das hängt vom Stein und vom Zustand ab. Deshalb kommen wir vorbei und reinigen eine Probefläche. Danach bekommen Sie einen festen Preis, schriftlich.": "It depends on the stone and its condition. That is why we come round and clean a test area. Afterwards you get a fixed price in writing.",
    "Ohne Schutzschicht etwa alle zwei bis drei Jahre. Mit Schutzschicht viel seltener.": "Without a protective layer, roughly every two to three years. With one, far less often.",
    "Feinsteinzeug und Keramik": "Porcelain and ceramic",
    "Betonstein und Terrazzo": "Cast stone and terrazzo",
    "Die grünen und schwarzen Schleier an der Nordseite und unter den Fenstern sind Algen und Flechten. Sie sitzen auf der Farbe, nicht darunter. Ein neuer Anstrich deckt sie nur zu und kostet ein Vielfaches. Nach zwei bis drei Jahren sieht die Wand wieder genauso aus.": "The green and black films on the north side and under the windows are algae and lichen. They sit on top of the paint, not underneath. A new coat only covers them and costs many times more. After two to three years the wall looks the same again.",
    "Eine Reinigung entfernt das Grün mit den Wurzeln und legt die alte Farbe frei. Erst wenn die Wand sauber ist, sieht man, ob ein Anstrich überhaupt nötig ist. Meistens ist er es nicht.": "Cleaning removes the green along with its roots and exposes the old colour. Only once the wall is clean can you see whether paint is needed at all. Usually it is not.",
    "Wenig Druck, dafür mehr Zeit": "Low pressure, more time instead",
    "Eine Hauswand reinigt man nicht mit Kraft. Wir tragen ein Mittel auf, lassen es einwirken und spülen dann mit wenig Druck ab. So bleibt der Putz heil.": "You do not clean a house wall with force. We apply a product, let it work, then rinse at low pressure. That way the render stays intact.",
    "Was an der Wand herunterläuft, landet in Ihrem Beet. Deshalb nehmen wir Mittel, die sich in der Natur abbauen. Empfindliche Pflanzen decken wir ab.": "Whatever runs down the wall ends up in your flower bed. That is why we use products that break down naturally. We cover delicate plants.",
    "Bei Klinker gehen wir anders vor": "With brick we take a different approach",
    "Klinker ist hart, die Fuge dazwischen nicht. Wer mit vollem Druck darüber geht, spült die Fugen aus. Wir arbeiten so, dass die Fugen heil bleiben.": "Brick is hard, the mortar between it is not. Going over it at full pressure washes the joints out. We work so that the joints stay intact.",
    "Auf Wunsch mit Schutzschicht": "With a protective layer on request",
    "Eine Schutzschicht lässt Wasser abperlen. Das Grün kommt dadurch viel später zurück. Fünf Jahre Garantie, wie immer bei uns.": "A protective layer makes water bead off. The green comes back much later. Five-year guarantee, as always with us.",
    "gedämmte Fassaden": "Insulated facades",
    "Faserzementplatten (Eternit)": "Fibre cement panels (Eternit)",
    "Sockel und Vordächer": "Plinths and porch roofs",
    "Lohnt sich eine Reinigung gegenüber einem Anstrich?": "Is cleaning worth it compared with painting?",
    "Ja, deutlich. Ein Anstrich braucht ein Gerüst, Material und mehrere Tage Arbeit. Eine Reinigung braucht davon nur einen Bruchteil. Wie es bei Ihnen aussieht, sagen wir Ihnen nach der Besichtigung.": "Yes, clearly. Painting needs scaffolding, materials and several days of work. Cleaning needs only a fraction of that. We will tell you how it looks in your case after the inspection.",
    "In den allermeisten Fällen ja. Wenn der Putz feucht ist oder abplatzt, liegt das Problem tiefer. Dann sagen wir Ihnen, dass eine Reinigung nicht reicht.": "In the vast majority of cases, yes. If the render is damp or flaking, the problem lies deeper. Then we tell you that cleaning is not enough.",
    "Meistens nicht. Bis etwa zwölf Meter Höhe arbeiten wir mit einer langen Stange vom Boden aus. Das spart Ihnen das Gerüst.": "Usually not. Up to around twelve metres we work with a long pole from the ground. That saves you the scaffolding.",
    "Einmal sauber, fünf Jahre geschützt.": "Clean once, protected for five years.",
    "Eine frisch gereinigte Fläche ist offen wie am ersten Tag. Genau dann setzt sich neuer Schmutz am leichtesten fest. Ohne Schutzschicht sieht die Fläche nach zwei bis drei Jahren wieder aus wie vorher.": "A freshly cleaned surface is as open as on day one. That is exactly when new dirt settles most easily. Without a protective layer the surface looks the same as before after two to three years.",
    "Die Schutzschicht schließt die Poren, aber der Stein kann weiter atmen. Wasser perlt ab, statt einzuziehen. Öl und Schmutz halten nicht mehr. Und Moos braucht viel länger, bis es wiederkommt.": "The protective layer closes the pores, but the stone can still breathe. Water beads off instead of soaking in. Oil and dirt no longer stick. And moss takes much longer to return.",
    "Nur auf saubere, trockene Flächen": "Only on clean, dry surfaces",
    "Wer eine Schutzschicht auf schmutzigen Stein aufträgt, schließt den Schmutz mit ein. Das ist rausgeworfenes Geld. Wir tragen sie frühestens einen Tag nach der Reinigung auf, wenn alles trocken ist.": "Putting a protective layer on dirty stone seals the dirt in. That is money thrown away. We apply it no sooner than a day after cleaning, once everything is dry.",
    "Für jeden Belag das passende Mittel": "The right product for each surface",
    "Beton, Naturstein, Ziegel und Putz brauchen jeweils ein anderes Mittel. Ein Mittel für alles gibt es nicht. Jedenfalls keines, das lange hält.": "Concrete, natural stone, tile and render each need a different product. There is no single product for everything. At least none that lasts.",
    "Reichlich auftragen, nicht sparsam": "Apply generously, not sparingly",
    "Der Schutz entsteht durch die Menge, die in den Stein einzieht. Wer hier spart, spart an der Haltbarkeit.": "The protection comes from the amount that soaks into the stone. Saving here means saving on how long it lasts.",
    "Wird dieselbe Fläche innerhalb von fünf Jahren wieder stark schmutzig oder bewachsen, reinigen wir sie kostenlos noch einmal.": "If the same surface gets heavily dirty or overgrown again within five years, we clean it again free of charge.",
    "Es gibt matte Mittel, die kaum etwas verändern. Und solche, die den Stein etwas kräftiger wirken lassen. Sie entscheiden. An der Probefläche sehen Sie beides nebeneinander.": "There are matt products that change almost nothing. And ones that make the stone look a little richer. You decide. At the test area you see both side by side.",
    "Nicht, wenn das richtige Mittel gewählt wird. Für Treppen und Schrägen nehmen wir Mittel, die rutschfest bleiben.": "Not if the right product is chosen. For steps and slopes we use products that stay non-slip.",
    "Wird dieselbe Fläche in den fünf Jahren wieder stark schmutzig oder bewachsen, reinigen wir kostenlos nach. Schäden durch Kratzer oder bauliche Mängel gehören nicht dazu.": "If the same surface gets heavily dirty or overgrown again within the five years, we clean it again free of charge. Damage from scratches or building defects is not included.",
    "Ja. Die Fläche muss dafür aber noch einmal gereinigt werden. Direkt nach der ersten Reinigung ist es deutlich einfacher.": "Yes. But the surface has to be cleaned again first. Straight after the first clean it is much simpler.",
    "Pflaster, Einfahrten und Höfe": "Paving, driveways and yards",
    "Naturstein mit atmendem Schutz": "Natural stone with breathable protection",
    "Hauswände und Sockel": "House walls and plinths",
    "So arbeiten wir. Vier Punkte, auf die es ankommt.": "How we work. Four points that matter.",
    "Wir kommen vorbei und reinigen etwa einen Quadratmeter als Probe. Sie sehen das Ergebnis bei sich zu Hause. Nicht auf einem Foto von jemand anderem.": "We come round and clean about one square metre as a test. You see the result at your own home. Not in someone else’s photo.",
    "Das werden wir oft gefragt.": "These are the questions we get asked most."
}
